### ISSUE TITLE
bluesim.tcl: -w flag accepted but causes errors

### ISSUE THREAD

**Issue by arichardson** [B-Lang-org/bsc#134]
```
Error: Unexpected additional arguments: "wait".
    invoked from within
"sim load $model_name $top_module wait"
    invoked from within
"if {$wait} {
sim load $model_name $top_module wait
} else {
sim load $model_name $top_module
}"
```

**Comment by quark17** [comment]
Ah, sorry about that.  Thanks for reporting it.  I've addressed this with commit 8c3bac51, by removing the -w flag.

Since `bsc` no longer accepts the `-wait-for-license` flag, I figured this backwards incompatibility is also OK.  Better to do it now than later.
