### ISSUE TITLE
Compilation error during build

### ISSUE THREAD

**Issue by debjyoti0891** [B-Lang-org/bsc#141]
ghc version: 8.0.2

`[181 of 226] Compiling Depend           ( Depend.hs, /imec/other/nmorph/bhatta53/private/software/bsc/src/comp/../../build/Depend.o )

Depend.hs:78:46: error:
    * Couldn't match expected type `time-1.10:Data.Time.Clock.Internal.UTCTime.UTCTime'
                  with actual type `time-1.6.0.1:Data.Time.Clock.UTC.UTCTime'
      NB: `time-1.6.0.1:Data.Time.Clock.UTC.UTCTime'
            is defined in `Data.Time.Clock.UTC' in package `time-1.6.0.1'
          `time-1.10:Data.Time.Clock.Internal.UTCTime.UTCTime'
            is defined in `Data.Time.Clock.Internal.UTCTime'
                in package `time-1.10'
    * In the first argument of `floor . utcTimeToPOSIXSeconds', namely
        `utcTime'
      In the expression: (floor . utcTimeToPOSIXSeconds) utcTime
      In an equation for `s': s = (floor . utcTimeToPOSIXSeconds) utcTime
make[2]: *** [bsc] Error 1
make[2]: Leaving directory `/imec/other/nmorph/bhatta53/private/software/bsc/src/comp'
make[1]: *** [install] Error 2
make[1]: Leaving directory `/imec/other/nmorph/bhatta53/private/software/bsc/src'
make: *** [install] Error 2`

**Comment by bpfoley** [comment]
This looks like you've got some sort of cabal misconfiguration on your system. It appears you have two versions of the time package installed: time-1.10 and time-1.6.0.1, and they're conflicting with each other.
