### ISSUE TITLE
itcl/itk linking

### ISSUE THREAD

**Issue by quark17** [B-Lang-org/bsc#149]
In PR #146, the issue was raised that itcl/itk libraries may not be available in the same place as tcl/tk (since itcl/itk is intended to be dynamically loaded in tcl).  The issue was deferred from that PR, so I'm opening this ticket to record it.

The tcl interpreter has a search path where index files (`pkgIndex.tcl`) can be found, that declare the available packages, and give arbitrary code for how to load them.  For example, as @bpfoley pointed out in the PR thread:

    $ tclsh
    % package require Itcl
    3.4
    % package ifneeded Itcl 3.4
    load /usr/lib/x86_64-linux-gnu/libitcl3.4.so.1 Itcl

And here is the search path on that same system:

    % puts $auto_path
    /usr/share/tcltk/tcl8.6 /usr/share/tcltk /usr/lib /usr/local/lib/tcltk /usr/local/share/tcltk /usr/lib/tcltk/x86_64-linux-gnu /usr/lib/tcltk /usr/lib/tcltk/tcl8.6

On this system, under `/usr/lib/tcltk/x86_64-linux-gnu/` are `itcl3.4` and `itk3.4` directories that contain `pkgIndex.tcl` files declaring `Itcl` and `Itk`:

    if {![package vsatisfies [package provide Tcl] 8.6]} {return}
    package ifneeded Itcl 3.4 [list load [file join /usr lib x86_64-linux-gnu "libitcl3.4.so.1"] Itcl]

(I would guess that the search of `auto_path` must recurse into subdirectories?)

In addition to this kind of searching, the tcl interpreter can also declare that some packages are statically available.  (This is from the point of view of the interpreter; the library might be dynamically loaded by the executable when run, but that's still considered "static" because the library is already loaded by the time the interpreter executable is running.)  In `bluetcl_Main.hsc` (and `bluewish_Main.hsc`), we declare that itcl (or itk) is available:

    // Itcl startup
    if (Itcl_Init(interp) != TCL_OK) {
      fprintf(stderr,"Unable to start itcl -- %s\n", Tcl_GetStringResult(interp));
      exit (-1);
    }
    Tcl_StaticPackage(interp, "Itcl", Itcl_Init, Itcl_SafeInit);

**NOTE:** At some point (maybe when we unvendored tcl/tk and itcl/itk?) we seem to have also changed the linking of those libraries to be dynamic instead of static.  So we are now requiring that itcl/itk be available in the user's environment, not just the build environment!

I think we need to go in one of two directions: (A) Fix the linking to be static linking (with `.a` files), so that we are not requiring that Itcl/Itk be installed in the user's environment (for the right version of tcl/tk) and further that we're not requiring that tcl/tk (of the right version) be installed in the user's environment either.  Or (B) we go all-in on using the system version of tcl/tk and itcl/itk.

If we want to go all in, is it sufficient to just remove the static declaration from the `.hsc` files?  We'd still be producing `bluetcl` and `bluewish` binaries that expect to dynamically link with tcl/tk on the system.  Would it be any more portable if we eliminated `bluetcl` and `bluewish` binaries, and just made the bluespec commands into library that gets loaded into `tclsh` the same way that itcl/itk does?  Or would that library still be tied to a specific tcl/tk, in which case it doesn't hurt to keep `bluetcl` and `bluewish` binaries (since either way we'd be requiring the user's system to have a specific version of tcl/tk installed)?

FYI, I notice that no code in the `bsc` repo has `package require Itcl`.  This seems to only exist in the Workstation GUI (which is not yet open source, but will come, probably in its own repo).

Anyway, I'm leaning towards eliminating mentions of Itcl/Itk from the `Makefile` and `.hsc` -- keeping the `-l` linking of tcl/tk for the `bluetcl` and `bluewish` binaries, but no mention of itcl/itk -- and relying on the `auto_path` to load itcl/itk where needed.  I would also be OK with going back to statically linking both tcl/tk and itcl/itk.  What do folks think?

**Comment by thotypous** [comment]
Thank you for your careful analysis of the issue!

> (I would guess that the search of `auto_path` must recurse into subdirectories?)

It seems to search `$path/*/pkgIndex.tcl` for each path in `$auto_path`:

```
% set auto_path /usr
/usr
% package require Itcl
can't find package Itcl
% set auto_path /usr/lib
/usr/lib
% package require Itcl
4.2.0
```

> Would it be any more portable if we eliminated bluetcl and bluewish binaries, and just made the bluespec commands into library that gets loaded into tclsh the same way that itcl/itk does?

From a sysadmin and distribution package maintainer point of view, this seems like the ideal solution. However, there seems to be a lot of work involved. I'm a Haskell beginner, so I may be misinformed, but it seems like producing a C library containing Haskell code [is not trivial](https://ro-che.info/articles/2017-07-26-haskell-library-in-c-project).

> Anyway, I'm leaning towards eliminating mentions of Itcl/Itk from the `Makefile` and `.hsc` -- keeping the `-l` linking of tcl/tk for the `bluetcl` and `bluewish` binaries, but no mention of itcl/itk -- and relying on the `auto_path` to load itcl/itk where needed.

This seems like a very good solution. This way we eliminate bsc's dependency on itcl/itk. The dependency can then be moved to BDW when it is released. This fits very nicely if it is released in a separate repository as planned. At the distribution side, BDW can then be packaged as a separate package.

> I would also be OK with going back to statically linking both tcl/tk and itcl/itk.

I'm against going back to statically linking. IMHO this should be solved by the artifact delivery method. If it is a distribution package, it should be rebuilt if tcl/tk or itcl/itk versions change. If it is a container, a [nix-makeself tarball](https://github.com/B-Lang-org/bsc/issues/116#issue-579576421), or (eek) a snap, it is already packaged with the right version of all dependencies.
