### ISSUE TITLE
tclsh not installed into right location

### ISSUE THREAD

**Issue by flokli** [B-Lang-org/bsc#24]
`tclIndex.sh` tries to invoke `tclsh`, however, the `tclsh` binary gets installed into a wrong location,

`source/src/tcltk/tcltk8.5.4/tcl8.5.4/unix/../../../inst/bin/tclsh8.5`, which means `source/src/tcltk/inst/bin/tclsh8.5`.

I assume this wasn't caught, because there's another `tclsh` in `$PATH`.

**Comment by flokli** [comment]
Except for the HTcl part, we probably could also simply use `tcl` from `$PATH`.

**Comment by thoughtpolice** [comment]
See also #28.
