### ISSUE TITLE
Create more accesible documentation/Port existing docs

### ISSUE THREAD

**Issue by rishubn** [B-Lang-org/bsc#287]
As a newcomer to Bluespec, one barrier has been finding documentation and learning materials. It seems that most of this content is available in official PDFs, various talks, a wiki page, and university course lectures scattered across the web. The "docs" button on the README page does not point to any of these and just redirects to the same page. It would really be helpful if the current available documentation could be ported to ReadTheDocs or something similar. Since the bsc compiler repository is the highest ranked repository and often is the landing page for new users, a first step could be to setup RtD or some similar service for this repository which points to existing learning material, like the [Intro Guide.](https://github.com/kcamenzind/BluespecIntroGuide/blob/master/BluespecIntroGuide.md). Another good move would be to port the tutorial and user guide PDFs to RtD, this could easily be done with the PDF sources which you most likely hold internally.

Personally, I would be more than willing to help contribute to these docs, and I know a few others who are interested in BlueSpec who would do the same.

**Comment by quark17** [comment]
I agree that this needs to be improved!  I think that this is covered by existing issue #36 , so I will mark this as a duplicate and comment there with an update.  Thanks!
