### ISSUE TITLE
Using the Bluespec compiler

### ISSUE THREAD

**Issue by nishanthsmurthy24** [B-Lang-org/bsc#320]
To run the BSC tools, I have to add the "bin" directory to the PATH.

For my computer the installation directory is /home/mjolnir/inst/bin 

So the command is 
$export PATH=$/home/mjolnir/inst/bin:$PATH

But when I run the $bsc -help command it says,

Command 'bsc' not found, but there are 18 similar ones.
 
Please help me solve this.

**Comment by quark17** [comment]
> So the command is
> $export PATH=$/home/mjolnir/inst/bin:$PATH

There should be no `$` before the directory.  Is that a typo?
```
export PATH=/home/mjolnir/inst/bin:$PATH
```
