### ISSUE TITLE
Couldn't detect libstdc++.so.6 

### ISSUE THREAD

**Issue by saw235** [B-Lang-org/bsc#394]
Getting the following error when running the simulation.

`libstdc++.so.6: cannot open shared object file: No such file or directory`

My Makefile
```
build_tb :
	mkdir -p $(WORKDIR)
	bsc $(BUILDFLAGS) -sim -g mkTb $(SRCDIR)/Tb.bsv 
	bsc $(BUILDFLAGS) -o $(WORKDIR)/tb_simrun -sim -e mkTb

run-sim : build_tb 
	$(WORKDIR)/tb_simrun 
```

Not sure what is happening here because `locate libstdc++.so.6 | head -n 1` gives me 
`/usr/lib/x86_64-linux-gnu/libstdc++.so.6`
so clearly the library is installed.

When I move the `libstdc++.so.6` to run dir, the simulation works fine.

**Comment by quark17** [comment]
Hm, I've never seen this before.  You might try using `strace` to dump additional information:
```
$ strace  -o trace.txt  $(WORKDIR)/tb_simrun
```
This will create a file `trace.txt` that contains a trace of the steps taken to execute the program.  For example, you should see statements for each attempt to find the library in the library load path.  When it tries a directory that does not contain the library, you should see this:
```
openat(AT_FDCWD, "/path/to/bsc/inst/lib/SAT/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```
and then when it succeeds to find the library, it would look like this:
```
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
```
If the file is failing to load for other reasons, there might be an error message providing more information.

Another piece of information could be to run `ldd` on the `.so` file:
```
$ ldd $(WORKDIR)/tb_simrun.so
...
libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6ac333f000)
...
```
You might also be able to see the search path with this command:
```
ld --verbose | grep SEARCH_DIR | tr -s ' ;' \\012
```
