### ISSUE TITLE
hexDigitToInteger failure for lower case HEX chars b,c,d,e,f

### ISSUE THREAD

**Issue by tiefseeudo** [B-Lang-org/bsc#440]
Hello,
I tried to convert some hex values I read from a file into Integer values, which caused the compiler to crash.

Reproduce:
```
module mkTestbenchF();

    String test = "bcdef";  
    let charList = stringToCharList(test);
    Integer number = 0;

    for(Integer i = 0; i < length(charList); i = i + 1) begin
        let asInt = hexDigitToInteger(charList[i]);
        number = number + asInt* 16**i;
    end

    mkAutoFSM(
        seq
            $display("Result: %d", number);
        endseq
    );

endmodule
```

Issue in source code of hexDigitToInt function:
![image](https://user-images.githubusercontent.com/33375734/150673633-8c78d341-508c-4408-b1e6-0ee4af1d24b8.png)

Maybe the error message could be adjusted to "hexDigitToInteger: not a digit: `<character>'" as well, the current one is a little bit misleading.
I got my code to work with a temporary fix where I just convert the chars to upper case.

**Comment by quark17** [comment]
Yes, these fixes look good.  Thank you for reporting this.

When the `Printf` library was added, it needed `integerToHexDigit`, but all four combinations were added (to and from integer and bit).  I would guess that the other combinations have not really been used.  Apologies for the bug.
