### ISSUE TITLE
*Electronics* Hardware Description Language

### ISSUE THREAD

**Issue by hoijui** [B-Lang-org/bsc#473]
Hello! :-)
comming here as a complete newb, I read "Bluespec **Hardware Description Language**", and I think:

> Oh nice! I can design a chair in a high-level programming language with this!

But reading on.. it seems, it can only deal with electronics.. right?
It would be nice if this was clear from the start... could it maybe be included in the README at the top?

**Comment by rsnikhil** [comment]
Thank you for your comment. I've added "digital electronic" in the opening paragraph.

Actually BSV and BH could in principle also be used to design digital optonic and fluidic circuits (not just electronic), but compilers for those targets are left for the future.   :-)
