### ISSUE TITLE
Enable CI for Ubuntu 22.04

### ISSUE THREAD

**Issue by kenta2** [B-Lang-org/bsc#483]
github now has "beta" runners for continuous integration for Ubuntu 22.04.

**Comment by quark17** [comment]
I have a branch in my local repo ([here](https://github.com/quark17/bsc/tree/add-new-vms)) on which I've added Ubuntu 22.04 and also macOS 12.  I will submit it as a PR, but currently there's a tool in the CI that's failing to build on the Ubuntu 22.04 VM.  Specifically, in the Toooba repo, which we test the BSC build on:
```
gcc -g  -o elf_to_hex  elf_to_hex.c  -lelf
[17](https://github.com/quark17/bsc/runs/7381112144?check_suite_focus=true#step:9:18)
/tmp/ccivqGbz.o: in function `c_mem_load_elf':
[18](https://github.com/quark17/bsc/runs/7381112144?check_suite_focus=true#step:9:19)
/home/runner/work/bsc/Toooba/Tests/elf_to_hex/elf_to_hex.c:94:(.text+0x25a): relocation truncated to fit: R_X86_64_PC32 against symbol `bitwidth' defined in .bss section in /tmp/ccivqGbz.o
...
```
