### ISSUE TITLE
yices-src-for-bsc-2022.01.tar.gz not in gzip format

### ISSUE THREAD

**Issue by vowstar** [B-Lang-org/bsc#498]
In release: https://github.com/B-Lang-org/bsc/releases/download/2022.01/yices-src-for-bsc-2022.01.tar.gz

gzip: yices-src-for-bsc-2022.01.tar.gz: not in gzip format

file /var/cache/distfiles/yices-src-for-bsc-2022.01.tar.gz 
/var/cache/distfiles/yices-src-for-bsc-2022.01.tar.gz: POSIX tar archive

It is a POSIX tar archive, this suffix is ​​misleading.

**Comment by quark17** [comment]
Thank you for bringing this to our attention!  I have fixed it for both the 2022.01 release and 2012.12.01 snapshot.
