### ISSUE TITLE
Clarification on match assignments with structs

### ISSUE THREAD

**Issue by yannickl96** [B-Lang-org/bsc#500]
Hello there!

I am currently writing code using __pattern matching assignment statements__ and noticed the following behaviour:
According to the pattern grammar inside the current language reference guide the way to match a struct should be as follows (full code example is provided at the end of the issue):
```
match tagged A {sa: .a, sb: .b, sc: .c} = t;
```
where ``A`` is the name of a struct type, ``sa, sb, sc`` are struct members and ``.a, .b, .c`` are patterns binding the selected members in struct expression ``t`` to local variables ``a, b, c``.
However, the above code yields the following error message when compiling:
```
Error: "TestStruct.bsv", line 12, column 38: (T0046)
  Only matching of structs and tuples is supported in this context.
  The following pattern is not supported:
    A { sa = a; sb = b; sc = c; }
  Consider matching this pattern with a case statement instead.
```

In order to get the code to compile, we have to drop the ``tagged`` keyword from the struct pattern, i.e.
```
match A {sa: .a, sb: .b, sc: .c} = t;
```

I suggest to update the documentation (the follow-up paragraph on struct patterns also mentions the ``tagged`` keyword).

Best,
Yannick

Full working code example:
```
package TestStruct;
        typedef struct {
        int sa;
        int sb;
        Bool sc;
        } A deriving(Bits);

        module mkTestStruct();
                Reg#(A) t <- mkReg(A{sa: 42, sb: 1337, sc: True});

                rule f;
                        match A {sa: .a, sb: .b, sc: .c} = t;
                        $display("(%d,%d,%b)", a, b, c);
                        $finish();
                endrule
        endmodule
endpackage
```
Compiler command used:
```bsc -u -sim -g mkTestStruct TestStruct.bsv```

**Comment by quark17** [comment]
Thank you (belatedly) for submitting this.  There were a series of commits around April-May 2021 that cleaned up the BSV parsing of structs versus tagged unions -- before that, BSC would mostly ignore whether `tagged` was used in the pattern or not, and now BSC is strict that `tagged` is for tagged unions and structs are without it (and it uses that info to help disambiguate types with similar constructor or field names).

I do see that, at the start of Chapter 11 ("Pattern Matching"), the definition of the grammar term `structPattern` has `tagged` in it, and that the later paragraph with a textual description also mentions `tagged`.  I will fix those two places.  I don't see any code examples or anything else that needs to change, but let me know if I've missed something.
