### ISSUE TITLE
 warning: command-line option '-fpermissive' is valid for C++/ObjC++ but not for C

### ISSUE THREAD

**Issue by quentinschibler** [B-Lang-org/bsc#509]
I have been getting this warning when compiling with c function imported. It looks like you're using a C++ flag using a C compiler ?

**Comment by quark17** [comment]
This is a known issue that's benign, but should probably be resolved.  This flag was added in 2011 as part of getting BSC to compile with GCC 4.6.  I assume it can probably be removed now?  It probably didn't work with other compilers, anyway, although it's possible that Clang has added it.  The GCC flag is described as downgrading warnings, but it's really considered by GCC to be a "dialect flag" and therefore only applies to C++.  (In the [change log for GCC 4.6](https://gcc.gnu.org/gcc-4.6/changes.html), it mentions two language changes and in both cases that `-fpermissive` can be used to get the old behavior.)  BSC does know when it's calling a C compiler vs a C++ compiler, and so we could update BSC to only provide the flag for C++; but it might be best to remove the flag altogether and see if we still need it.  (If users need it, for compiling their provided code, they can add the flag via several means (`-Xc++` argument or `CXXFLAGS` or `BSC_CXXFLAGS`) all of which would only apply when invoking the C++ compiler.

BSC has three places where it invokes the C/C++ compiler (all in `bsc.hs`): compiling Bluesim C++ files, compiling the user's imported C/C++ files, and compiling the VPI files that wrap the user's code.  In each of these cases, we provide the flag `-fpermissive`.  (For Bluesim C++ files, we also provide `-Wno-uninitialized`.)  For Bluesim, the files are always C++.  For the VPI and user files, BSC checks the suffix to decide which compiler to use -- and which flags to use!  The `-fpermissive` flag should have been included based on that too; but probably can just be removed now.
