### ISSUE TITLE
deriving Bitwise for enum

### ISSUE THREAD

**Issue by pwang7** [B-Lang-org/bsc#517]
Hi there, how to implement `Bitwise` for `enum`?

I have some kind of flags implemented as `enum`, and I'd like it support bitwise operations among flags, such `A | B`, `C | B`:
```Bluespec
typedef enum {
  A = 1,
  B = 2,
  C = 4,
  D = 8
} Flags deriving(Bits, Bitwise, Eq);
```
But deriving `Bitwise` for `enum` is not allowed in BSV.

**Comment by krame505** [comment]
Deriving isn't supported for the `Bitwise` type class, you would need to write an instance manually.  You can define it in terms of the `Bit` instance for `Flags`, e.g.
```
instance Bitwise Flags where
  (&) x y = unpack (pack x & pack y)
  ...
```
using the classic syntax, I'm not familiar with the BSV syntax but it should be logically the same.

**Comment by pwang7** [comment]
> Deriving isn't supported for the `Bitwise` type class, you would need to write an instance manually. You can define it in terms of the `Bit` instance for `Flags`, e.g.
> 
> ```
> instance Bitwise Flags where
>   (&) x y = unpack (pack x & pack y)
>   ...
> ```
> 
> using the classic syntax, I'm not familiar with the BSV syntax but it should be logically the same.

Thanks!
