### ISSUE TITLE
Vim syntax highlighting doesn't work

### ISSUE THREAD

**Issue by meschi** [B-Lang-org/bsc#526]
Hi,

I've just noticed that the guide to install syntax highlighting for vim misses one critical piece.
You have to add following line to .vimrc so that vim connects the syntax definition to the bluespec file extension
`au BufRead,BufNewFile *.bs set filetype=bsv`
This info is missing in the following README file, besides that the instructions do work for me.

https://github.com/B-Lang-org/bsc/blob/main/util/vim/README

**Comment by quark17** [comment]
Thank for posting, and sorry for the delay in responding!

The line you show will set the filetype to BSV for files ending in `.bs`.  However, that extension is for BH syntax (also called Classic), and not for BSV syntax!  The provided Vim tools only support BSV and should not for be used for BH files (with that extension).  If you look in `util/vim/ftdetect/bsv.vim`, you will see that auto-detection is already added for files ending in `.bsv`:
```
au BufNewFile,BufRead   *.bsv   set filetype=bsv
```

We would welcome the contribution of Vim syntax tools for BH, if someone has written it and would like to submit it to the BSC repo.  The BH/Classic syntax is similar to Haskell, so a workaround for the moment would be to create a file `~/.vim/ftdetect/bh.vim` with the following line, that tells Vim to use Haskell highlighting and indentation:
```
au BufNewFile,BufRead   *.bs    set filetype=haskell
```
