### ISSUE TITLE
Graphical User Interface missing

### ISSUE THREAD

**Issue by akb2020** [B-Lang-org/bsc#69]
I remember to use a nice GUI when I used BSV earlier. I have just compiled this open source version. But I could not find any way to launch the GUI. I guess that it is not available any more. But I would like to suggest to make that GUI available again so that people like me can use the compiler and simulator in a comfortable manner.

Please reply if you are going to make it available.

**Comment by quark17** [comment]
We will probably release the GUI, but it requires some cleanup first, so I can't say when that will be.

**Comment by quark17** [comment]
Good news! The BSC Development Workstation (BDW) is now available: https://github.com/B-Lang-org/bdw
