### ISSUE TITLE
Missing libraries (TLM3, Axi, etc.)

### ISSUE THREAD

**Issue by tupipa** [B-Lang-org/bsc#79]
Hi All,

I am a newbie to Bluespec and playing with the open sourced compiler to compile an open source processor [here](https://github.com/CTSRD-CHERI/beri). The warnings/errors are as following:

```
Warning: Command line: (S0091)
  Removing a directory from the path specified with the -p flag, because it
  could not be opened.
  Directory:
    /root/lab/cheri/beri/bsc/bsc/inst/lib/Libraries/Axi
  System message:
    does not exist
Warning: Command line: (S0091)
  Removing a directory from the path specified with the -p flag, because it
  could not be opened.
  Directory:
    /root/lab/cheri/beri/bsc/bsc/inst/lib/Libraries/Contrib/NonPipelinedMath
  System message:
    does not exist
Warning: Command line: (S0091)
  Removing a directory from the path specified with the -p flag, because it
  could not be opened.
  Directory:
    /root/lab/cheri/beri/bsc/bsc/inst/lib/Libraries/TLM3
  System message:
    does not exist
checking package dependencies
Error: "../../cherilibs/trunk/CheriAxi.bsv", line 55, column 1: (S0034)
  Cannot find the file `TLM.defines' to be included
Makefile:514: recipe for target 'build_fpu_sim/sim' failed
make: *** [build_fpu_sim/sim] Error 1

```

It seems there are some missing libraries compared to the [licensed version](https://bluespec.com/2019/05/04/bluespec-releases-version-beta-2/) of the compiler, such as TLM3, Axi, NonPiplelineMach, etc. Is there anybody trying to add them? Or is there any legal issue preventing them to be open sourced? If these libraries are allowed to be open sourced, is it possible for me to contribute to this repository by simply moving the libraries from the licensed version to this open sourced version?

Thanks.
Lele Ma

**Comment by bpfoley** [comment]
Good news: they were open sourced earlier this week in a separate github repository.

See https://github.com/B-Lang-org/bsc-contrib
